plugins { id 'com.android.application' }

android {
    namespace 'com.hilal.ibadet'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hilal.ibadet'
        minSdk 26
        targetSdk 35
        versionCode 84
        versionName '5.42-firebase-apk-startup-clean'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'androidx.credentials:credentials:1.7.0-alpha03'
    implementation 'androidx.credentials:credentials-play-services-auth:1.7.0-alpha03'
    implementation 'com.google.android.libraries.identity.googleid:googleid:1.2.1'
    implementation platform('com.google.firebase:firebase-bom:34.3.0')
    implementation 'com.google.firebase:firebase-database'
}
